--liquibase formatted sql
--changeset denMg:2

CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  telegram_user_id BIGINT NOT NULL,
  telegram_chat_id BIGINT,
  username VARCHAR(255),
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  email VARCHAR(255),
  first_login_date TIMESTAMP,
  state VARCHAR(255),
  is_active BOOLEAN DEFAULT 'false',
  CONSTRAINT app_user_pk PRIMARY KEY (id)
);

--rollback DROP TABLE app_user;
