--liquibase formatted sql
--changeset denMg:5

CREATE TABLE IF NOT EXISTS app_photo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  telegram_file_id VARCHAR(255) NOT NULL,
  file_size INTEGER,
  binary_content_id BIGINT NOT NULL,
  CONSTRAINT app_photo_pk PRIMARY KEY (id),
  CONSTRAINT binary_content_fk FOREIGN KEY (binary_content_id) REFERENCES binary_content(id)
);

--rollback DROP TABLE app_photo;
