--liquibase formatted sql
--changeset denMg:4

CREATE TABLE IF NOT EXISTS app_doc (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  telegram_file_id VARCHAR(255) NOT NULL,
  doc_name VARCHAR(255),
  mime_type VARCHAR(255),
  file_size INTEGER,
  binary_content_id BIGINT NOT NULL,
  CONSTRAINT app_doc_pk PRIMARY KEY (id),
  CONSTRAINT binary_content_fk FOREIGN KEY (binary_content_id) REFERENCES binary_content(id)
);

--rollback DROP TABLE app_doc;
